//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fare
    {
        public string 序号 { get; set; }
        public Nullable<int> 外滩 { get; set; }
        public Nullable<int> 东方明珠 { get; set; }
        public Nullable<int> 城隍庙 { get; set; }
        public Nullable<int> 上海环球金融中心 { get; set; }
        public Nullable<int> 上海野生动物园 { get; set; }
        public Nullable<int> 朱家角古镇 { get; set; }
        public Nullable<int> 上海博物馆 { get; set; }
        public Nullable<int> 新天地 { get; set; }
        public Nullable<int> 上海杜莎夫人蜡像馆 { get; set; }
        public Nullable<int> 欢乐谷 { get; set; }
        public Nullable<int> 上海科技馆 { get; set; }
        public Nullable<int> 田子坊 { get; set; }
        public Nullable<int> 豫园 { get; set; }
        public Nullable<int> 上海植物园 { get; set; }
        public Nullable<int> 上海海洋水族馆 { get; set; }
        public Nullable<int> 金茂大厦88层观光厅 { get; set; }
        public Nullable<int> 外白渡桥 { get; set; }
        public Nullable<int> 巧克力开心公园 { get; set; }
        public Nullable<int> 佘山国家森林公园 { get; set; }
        public Nullable<int> 七宝老街 { get; set; }
        public Nullable<int> 宋庆龄故居纪念馆 { get; set; }
        public Nullable<int> 徐家汇天主教堂 { get; set; }
        public Nullable<int> 中华艺术宫 { get; set; }
        public Nullable<int> 南京路步行街 { get; set; }
        public Nullable<int> 张爱玲故居 { get; set; }
        public Nullable<int> 人民广场 { get; set; }
    
        public virtual 景点介绍 景点介绍 { get; set; }
    }
}
