//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class number
    {
        public string 序号 { get; set; }
        public string C_1 { get; set; }
        public string C_2to3 { get; set; }
        public string C_4to8 { get; set; }
    
        public virtual 景点介绍 景点介绍 { get; set; }
    }
}
